export { default as Navbar } from './Navbar'
export { default as HomePage } from './Homepage'
export { default as CryptoDetails } from './CryptoDetails'
export { default as Cryptocurrencies } from './Cryptocurrencies'
export { default as News } from './News'